import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import "@/styles/globals.css";
import { AsideLeft, AsideRight } from "@/components/Aside";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="flex justify-center items-start w-[100%] mt-20 gap-4">
          <AsideLeft />
          {children}
          <AsideRight />
        </main>
      </body>
    </html>
  );
}
